// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLc2NjF9IHIUlKmGXcu-OFtqBe3M4dc6E',
    appId: '1:132663822038:web:bb898af2b65fccbe036b77',
    messagingSenderId: '132663822038',
    projectId: 'euphoria5472',
    authDomain: 'euphoria5472.firebaseapp.com',
    storageBucket: 'euphoria5472.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsqQzU-e-PdYvEegZOqKNve-YKqVH2pWg',
    appId: '1:132663822038:android:a095fc991b0e5d26036b77',
    messagingSenderId: '132663822038',
    projectId: 'euphoria5472',
    storageBucket: 'euphoria5472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXp9ELdjhVDtLqJraIYG_BNLYV-DAJnac',
    appId: '1:132663822038:ios:f776537a6e665369036b77',
    messagingSenderId: '132663822038',
    projectId: 'euphoria5472',
    storageBucket: 'euphoria5472.appspot.com',
    androidClientId: '132663822038-oulu9pntpr9n1to1cv6hk2h55iuad3bf.apps.googleusercontent.com',
    iosClientId: '132663822038-3jb1mpklfi0of14qrjpbgnvbqkmh5uv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.euphoria',
  );
}
